---
- name: a play that verifies access to members of host group 'all'
  hosts: network
  gather_facts: no
  tasks:

  - name: Gather all legacy facts
    ios_facts:
      gather_subset: all

  - name: Gather only the config and default facts but not hardware facts
    ios_facts:
      gather_subset:
        - config
        - "!hardware"
      gather_network_resources:
        - interfaces
