---
- name: display host name, domain name, nameservers for ios devices
  hosts: ios

  tasks:

  - name: run the commands
    ios_command:
      commands:
      - sh run | include hostname
      - sh run | include ip domain name
      - sh run | include ip name-server
    register: result

  - debug:
      var: result.stdout



# use variables wisely

---
- name: display host name, domain name, nameservers for ios devices
  hosts: ios
  vars:
    includes:
      - hostname
      - domain name
      - name-server

  tasks:

  - name: run the commands
    ios_command:
      commands:
      - sh run | include {{ item }}
    loop: "{{ includes }}"
    register: result

  - debug:
      var: item.stdout
    loop: "{{ result.results }}"