---
- name: illustrating a simple condition
  hosts: cs01
  vars:
    show_interfaces: True

  tasks:
    - name: conditionally issue command
      vyos_command:
        commands:
          - show interfaces
      register: command_output
      when: show_interfaces == True

    - name: show command output
      debug:
        msg: "{{ command_output }}"
      when: show_interfaces == True