---
- name: Logging global check RENDERED state
  hosts: ioslab
  gather_facts: no
  tasks:
  - name: Render the ipv6 commands for provided configuration
    cisco.ios.ios_logging_global:
      config:
        - hosts: 
          - ipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7301
          - ipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7304
            discriminator: msglog01 severity includes 5
          - ipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7314
            sequence_num_session: True
          - ipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7314
            vrf: vpn1
          - ipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
            filtered: True
            stream: 10
          - ipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7354
            transport:
              tcp: 
                port: 514
      state: rendered
