---
- name: Logging check 2
  hosts: ioslab
  gather_facts: no
  tasks:
  - name: Logging buffered
    cisco.ios.ios_logging_global:
      config:
        - cns_events:
            severity: debugging
      state: merged
