---
- name: Logging check 4
  hosts: ioslab
  gather_facts: no
  tasks:
  - name: Logging simple discriminator
    cisco.ios.ios_logging_global:
      config:
        - origin_id:
            tag: ip
      state: merged
